;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Audio.Sounds.Atmo.RndAtmo",NewTagName="Audio.Sounds.Atmo.Random")
+GameplayTagList=(Tag="AreaName.Poor",DevComment="")
+GameplayTagList=(Tag="AreaName.Rich",DevComment="")
+GameplayTagList=(Tag="AreaName.Temple",DevComment="")
+GameplayTagList=(Tag="AreaName.Tutorial",DevComment="")
+GameplayTagList=(Tag="Audio.Sounds",DevComment="")
+GameplayTagList=(Tag="Audio.Sounds.Atmo",DevComment="")
+GameplayTagList=(Tag="Audio.Sounds.Atmo.Outside",DevComment="")
+GameplayTagList=(Tag="Audio.Sounds.Atmo.Random",DevComment="")
+GameplayTagList=(Tag="Audio.Sounds.Atmo.StartArea",DevComment="")
+GameplayTagList=(Tag="Audio.Sounds.Music",DevComment="")
+GameplayTagList=(Tag="Audio.Sounds.Music.MainMenu",DevComment="")
+GameplayTagList=(Tag="Audio.Sounds.Music.PlayLevel",DevComment="")
+GameplayTagList=(Tag="Audio.Sounds.Player",DevComment="")
+GameplayTagList=(Tag="Audio.Sounds.Player.FootSteps",DevComment="")

