// Copyright (c) 2026 Core Memory Entertainment GbR. All rights reserved.

#pragma once

#include "Audio/Environment/EnvironmentAudioTypes.h"

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "EnvironmentAudioZone.generated.h"

class UAudioComponent;
class UBoxComponent;
class UEnvironmentAudioPlayerComponent;

UCLASS()
class SHADOWSTEP_API AEnvironmentAudioZone : public AActor {
	GENERATED_BODY()
	
public:	
	AEnvironmentAudioZone();

protected:
	virtual void BeginPlay() override;
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

public:	
	bool ContainsWorldLocation(const FVector& WorldLocation) const;
	void HandlePlayerEnteredZone(UEnvironmentAudioPlayerComponent* PlayerComponent);
	void HandlePlayerExitedZone(UEnvironmentAudioPlayerComponent* PlayerComponent);

private:
	void CreateAudioComponentsIfNeeded();
	UAudioComponent* GetOrCreateAudioComponent(int32 LoopIndex);

	void FadeInLoopSound(uint32 LoopIndex, UEnvironmentAudioPlayerComponent* PlayerComponent);
	void FadeOutLoopSound(uint32 LoopIndex);

	FVector ResolveLoopWorldLocation(const FEnvironmentZoneLoopSound& LoopSound, UEnvironmentAudioPlayerComponent* PlayerComponent) const;

private:
	//UEVENT(ParamNames = ("EnvironmentAudioPlayer"))
	//TEvent<UEnvironmentAudioPlayerComponent*> OnPlayerEntered{};

	//UEVENT(ParamNames = ("EnvironmentAudioPlayer"))
	//TEvent<UEnvironmentAudioPlayerComponent*> OnPlayerExited{};
	// 
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnPlayerEnteredBP, UEnvironmentAudioPlayerComponent*, EnvironmentAudioPlayer);
	UPROPERTY(BlueprintAssignable, Category = "Events")
	FOnPlayerEnteredBP OnPlayerEntered_BP;

	DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnPlayerExitedBP, UEnvironmentAudioPlayerComponent*, EnvironmentAudioPlayer);
	UPROPERTY(BlueprintAssignable, Category = "Events")
	FOnPlayerExitedBP OnPlayerExited_BP;

	UPROPERTY(VisibleAnywhere, Category = "Own|Environment Audio")
	TObjectPtr<USceneComponent> RootSceneComponent{ nullptr };

	// Visual shape of the zone.
	// This has no collisions.
	UPROPERTY(VisibleAnywhere, Category = "Own|Environment Audio")
	TObjectPtr<UBoxComponent> ZoneBounds{ nullptr };

	UPROPERTY(EditAnywhere, Category = "Own|Environment Audio|Sounds")
	TArray<FEnvironmentZoneLoopSound> LoopSounds{};

	UPROPERTY()
	TMap<int32, TObjectPtr<UAudioComponent>> LoopAudioComponents{};

	//// YAE_GENERATED_CODE_BEGIN
	//#pragma region UEVENT Generated Code (DO NOT TOUCH!)
	//// Generated by YetAnotherEventCodegen C#. Do not edit this region by hand.
	//// Re-run the generator after changing UEVENT declarations.

	//#pragma region Generated Blueprint Delegate for OnPlayerEntered
	//public:
	//DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnPlayerEnteredBP, UEnvironmentAudioPlayerComponent*, EnvironmentAudioPlayer);
	//UPROPERTY(BlueprintAssignable, Category = "Events")
	//FOnPlayerEnteredBP OnPlayerEntered_BP;
	//private:
	//uint8 _AutoBind_OnPlayerEntered = [this]() -> uint8 {
	//	OnPlayerEntered.SubscribeLambda(this, [this](auto&&... args) {
	//		OnPlayerEntered_BP.Broadcast(Forward<decltype(args)>(args)...);
	//	});
	//	return 0;
	//}();
	//public:
	//#pragma endregion

	//#pragma region Generated Blueprint Delegate for OnPlayerExited
	//public:
	//DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnPlayerExitedBP, UEnvironmentAudioPlayerComponent*, EnvironmentAudioPlayer);
	//UPROPERTY(BlueprintAssignable, Category = "Events")
	//FOnPlayerExitedBP OnPlayerExited_BP;
	//private:
	//uint8 _AutoBind_OnPlayerExited = [this]() -> uint8 {
	//	OnPlayerExited.SubscribeLambda(this, [this](auto&&... args) {
	//		OnPlayerExited_BP.Broadcast(Forward<decltype(args)>(args)...);
	//	});
	//	return 0;
	//}();
	//public:
	//#pragma endregion
	//private:
	//#pragma endregion
	//// YAE_GENERATED_CODE_END
};
